[build.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDOR",
    "OPENSSL_NO_PKG_CONFIG",
    "PKG_CONFIG_ALLOW_CROSS",
]

[target.aarch64-linux-android]
# Use the latest Android NDK image
image = "ghcr.io/cross-rs/aarch64-linux-android:latest"

[target.aarch64-linux-android.env]
volumes = ["CARGO_HOME=/root/.cargo"]
